USE [master]
GO

/****** Object:  Database [ProtocoloDB]    Script Date: 04/04/2023 00:45:57 ******/
CREATE DATABASE [ProtocoloDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProtocoloDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProtocoloDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProtocoloDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProtocoloDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProtocoloDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProtocoloDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProtocoloDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProtocoloDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProtocoloDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProtocoloDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProtocoloDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProtocoloDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProtocoloDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProtocoloDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProtocoloDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProtocoloDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProtocoloDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProtocoloDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProtocoloDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProtocoloDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProtocoloDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProtocoloDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProtocoloDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProtocoloDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProtocoloDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProtocoloDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProtocoloDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProtocoloDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProtocoloDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProtocoloDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProtocoloDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProtocoloDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProtocoloDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProtocoloDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProtocoloDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProtocoloDB] SET  READ_WRITE 
GO


